config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'
  put 'comments/search'

  get 'search_chirps/index'
  put 'search_chirps/search'

  get "find_friends/index"
  put "find_friends/search"

  put "follows/follow/:id" => "follows#follow", :as => 'follows_follow'
  put "follows/cancel/:id" => "follows#cancel", :as => 'follows_cancel'
  get 'follows/list'

  get 'chat/index'
  post 'chat/index'

  put "faces/update" => "faces#update"
  get 'faces/register'

##  get "users/face" => "users#face"
#  put "faces/register"

  devise_for :users
  resources :users do
    get 'face', to: 'users#face', on: :collection
  end

  ##get "chirps/face" => "chirps#face"
  ##get 'chirps', :to => 'chirps#index', :as => :user_root
  ##get 'chirps/photo' => 'chirps#photo'
    get 'chirps', :to => 'chirps#index', :as => :user_root

  resources :chirps do
    get 'face', to: 'chirps#face', on: :collection
    get 'photo', to: 'chirps#photo', on: :collection
    resources :comments
  end
  root :to => 'chirps#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/chirp.rb
class Chirp < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/chirps_controller.rb
class ChirpsController < ApplicationController
  before_action :set_chirp, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, only: [:index, :show, :new,
     :create, :edit, :destroy, :update, :photo]

  # GET /chirps
  # GET /chirps.json
  def index
    # This is the main entrance, after 'log-in'
    #if current_user and current_user.handle_name.blank?
    ##  session[:back_to_home] = true
    ##  redirect_to edit_user_path(current_user.id)
    ##else
    ##  @chirps = Chirp.all
    ##end
    if current_user
      if (current_user.handle_name == nil ||
          current_user.handle_name.length == 0)
          session[:back_to_home] = true
          redirect_to edit_user_path(current_user)
      end
    end
    @follows = Follow.where( user_id: current_user.id )
    @users = @follows.collect { |f| f.to_id }
    @users << current_user.id
    @chirps = Chirp.select{|c| @users.include?( c.user_id )}
    @chirps = @chirps.sort_by{ |c| c[:created_at] }.reverse
  end


  # GET /chirps/1
  # GET /chirps/1.json
  def show
  end

  # GET /chirps/new
  def new
    @chirp = Chirp.new
    @chirp.user_id = current_user.id
  end

  # GET /chirps/1/edit
  def edit
  end

  # POST /chirps
  # POST /chirps.json
  def create
    if params[:chirp][:photo]
      @file = params[:chirp][:photo]
      @chirp = Chirp.new(
        :chirp => params[:chirp][:chirp],
        :photo => @file.read,
        :file_name => @file.original_filename,
        :file_type => @file.content_type,
        :chirped_at => Time.now )
    else
      @chirp = Chirp.new(chirp_params)
    end
    @chirp.user_id = current_user.id

    respond_to do |format|
      if @chirp.save
        format.html { redirect_to @chirp, notice: 'Chirp was successfully created.' }
        format.json { render :show, status: :created, location: @chirp }
      else
        format.html { render :new }
        format.json { render json: @chirp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chirps/1
  # PATCH/PUT /chirps/1.json
  def update
    if params[:chirp][:photo]
      @file = params[:chirp][:photo]
      respond_to do |format|
        if @chirp.update(
           :chirp => params[:chirp][:chirp],
           :photo => @file.read,
           :file_name => @file.original_filename,
           :file_type => @file.content_type
         )
          format.html { redirect_to @chirp, notice: 'Chirp was successfully updated.' }
          format.json { render :show, status: :ok, location: @chirp }
        else
          format.html { render :edit }
          format.json { render json: @chirp.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        if @chirp.update(chirp_params)
          format.html { redirect_to @chirp, notice: 'Chirp was successfully updated.' }
          format.json { render :show, status: :ok, location: @chirp }
        else
          format.html { render :edit }
          format.json { render json: @chirp.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /chirps/1
  # DELETE /chirps/1.json
  def destroy
    @chirp.destroy
    respond_to do |format|
      format.html { redirect_to chirps_url, notice: 'Chirp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def photo
    @chirp = Chirp.find( params[:id] )
    send_data @chirp.photo, :filename => @chirp.file_name,
     :type => @chirp.file_type
  end

  def face
    face = Face.find( params[:id] )
    send_data face.content, :filename => face.name,
      :type=>face.content_type
  end

  def comment
    @chirp = Chirp.find( params[:id] )
    send_data @chirp.comment
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chirp
      @chirp = Chirp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chirp_params
      params.require(:chirp).permit( :user, :user_id, :chirp, :photo, :file_name, :file_type, :chirped_at)
    end
end

app/helpers/chirps_helper.rb
module ChirpsHelper
end

app/views/chirps/_form.html.erb
<%= form_with(model: chirp, local: true) do |form| %>
  <% if chirp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chirp.errors.count, "error") %> prohibited this chirp from being saved:</h2>

      <ul>
      <% chirp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= @chirp.user.email %>
  </div>

  <div class="field">
    <%= form.label :chirp %>
    <%= form.text_field :chirp, id: :chirp_chirp, size: "60x4" %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :chirp_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chirps/edit.html.erb
<h1>Editing Weidoo</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Show', @chirp %> |
<%= link_to 'Back', chirps_path %>

app/views/chirps/index.html.erb
<h1>Weidoo</h1>
<% if current_user %>
  <div><blockquote>
    Hello, <%= current_user.handle_name %>!<br />
    <table>
      <tbody>
        <tr>
          <td>
            <% if current_user.face %>
              <% face = current_user.face %>
              <% if face.content_type =~ /^image\/.*?(png|jpeg|gif|bmp)$/ %>
                <%= image_tag url_for({:action => 'face', :id=> face.id,
                    :filename => face.name}), :alt => face.name, :size => "60x60" %>
              <% end %>
            <% else %>
              <%= image_tag 'default_face.png', :alt => 'No Photo', :size => "60x60" %>
            <% end %>
          </td>
          <td>
             <%= link_to('Sign out', destroy_user_session_path, :method => :delete) %><br />
             <%= link_to 'Edit your info', edit_user_path( :id => current_user.id ) %><br />
             <%= link_to 'Change Password', edit_user_registration_path %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

<% if @message %>
  <h2><%= @message %></h2>
<% end %>

<table>
  <tbody>
    <% @chirps.each do |chirp| %>
    <tr>
       <td rowspan="2">
          <% if chirp.user.face %>
            <% face = chirp.user.face %>
            <% if face.content_type =~ /^image\/.*?(png|jpeg|gif)$/ %>
               <%= image_tag url_for({:action => 'face', :id=> face.id,
                    :filename => face.name,
                    :controller => "chirps"}), :alt => face.name,:size => "70x70"
               %>
            <% else %>
               <%= image_tag 'default_face.png', :alt => 'No Photo' %>
            <% end %>
          <% else %>
             <%= image_tag 'default_face.png', :alt => 'No Photo' %>
          <% end %>
        </td>
        <td><font color="green">@<%= chirp.user.handle_name %></font></td>
        <td><font color="blue"><%= chirp.created_at.strftime("%Y/%b/%d(%a) %p%l:%M") %></font></td>
        <td><%= link_to 'Edit', edit_chirp_path(chirp) %></td>
        <td><%= link_to 'Comments', comments_index_path(chirp) %></td>
      <tr>
        <td colspan="2"><%= chirp.chirp %></td>
        <td><%= link_to 'Destroy', chirp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
        <% if chirp.photo %>
          <tr>
            <td colspan="4">
              <p><blockquote>
                <% if chirp.file_type =~ /^image\/.*?(png|jpeg|gif)$/ %>
                  <%= image_tag url_for({:action => 'photo', :id=> chirp.id,
                    :filename => chirp.file_name, :controller => "chirps"}),
                    :size => "170x100",
                    :alt => chirp.file_name %>
                <% end %>
                <br />
              </p>
            </td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Weidoo', new_chirp_path %>

app/views/chirps/new.html.erb
<h1>New Weidoo</h1>

<%= render 'form', chirp: @chirp %>

<%= link_to 'Back', chirps_path %>

app/views/chirps/show.html.erb
<p>
  <strong>User:</strong>
  <%= @chirp.user.email %>
  <br />
  <strong>Chirp:</strong>
  <%= @chirp.chirp %>
  <br />
  <strong>Chirped at:</strong>
  <%= @chirp.chirped_at %>
</p>

<p>
  <% if @chirp.photo %>
    <strong>Photo:</strong>
    <% if @chirp.file_type =~ /^image\/.*?(png|jpeg|gif|bmp)$/ %>
      <%= image_tag url_for({:action => 'photo', :id => @chirp.id,
         :filename => @chirp.file_name} ), :alt => @chirp.file_name %>
    <% end %>
  <% end %>
</p>

<p>
</p>

<%= link_to 'Edit', edit_chirp_path(@chirp) %> |
<%= link_to 'Back', chirps_path %>